Calculator feature m4
Addis-Belete/calculator pull request #4
Opened 2021-07-18 11:24 UTC by Addis0943

2021-07-18 15:00 UTC, bellom requested changes
## Hi @Addis0943  :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 

# Status: Changes Required! ♻️ 

**Kindly check my comments under this review;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best**

2021-07-18 15:00 UTC, bellom commented on src/components/Display.js
> +/* eslint-disable react/prop-types */
With the ESLint inline comment, you are indirectly changing the linter's rules by disabling these rules, let's fix the codebase instead.

You had to add this line because you removed the `typechecking props` and also, you did these in all your component file ... 🤦 .

2021-07-18 15:00 UTC, bellom commented on src/components/Display.js
>  export default Display;
Kindly add the prop-types

2021-07-18 15:00 UTC, bellom commented on src/components/Button.js
>  export default Button;
Kindly add the prop-types

2021-07-18 15:00 UTC, bellom commented on src/components/ButtonPanel.js
> +          <Button name="*" handleClick={clickHandler} />
### [Optional]

I think it would be nice to use `x` than `*` just like the calculator on your phone or just as the one shared on pathwright.

2021-07-18 15:00 UTC, bellom commented on src/logic/calculator.js
> +
I think we need one more condition in here.....

Division by zero is not handled properly yet. Let's fix this.
The reason is that when a division by zero happens, we should return an error message like `division error`

Divide a number by zero (e.g. 4 / 0)

Console error from you app:
![image](https://user-images.githubusercontent.com/31897434/126072032-aa6556c8-7318-4926-bce8-045fa0cf6e91.png)

2021-07-19 05:04 UTC, Addis0943 commented
Hello TSE
Thank you for all your feedback. I did on all changes you requested except the last one (uncaught error) because I used a big.js(based on the requirement) to handle the calculation. so the big.js returns an Invalid error on console when number divided by zero. its all about big.js. So my be if there is a way to fix or change this error on big.js let me know and I will fix it.
Thank you in advance for your feedback again

2021-07-19 05:54 UTC, rindrajosia requested changes
Changes Required :red_circle:
To Highlight: :angel:

- Good job by trying to fix your codebase by adding typechecking props :+1: 

To improve :factory_worker: [REQUIRED]:

- [ ] I got an error related to prop-type, please fix it:
![1](https://user-images.githubusercontent.com/58552748/126108796-3e6b9eb4-a9aa-4c82-8b90-334ab168bf7c.gif)

- [ ] I got an error on my console when I am trying to dived number with 0;
![1](https://user-images.githubusercontent.com/58552748/126108867-4600754f-cfc5-40b8-8a02-a3109587ddf4.png)
To fix it, I will suggest you check if the divisor is 0 before making the operation. If it is 0, the result of the operation will be a message like "impossible" but if it is not 0, your APP will do the operation.

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

2021-07-19 05:54 UTC, rindrajosia commented on src/components/Button.js
> +/* eslint-disable react/prop-types */
|REQUIRED] With the ESLint inline comment, you are indirectly changing the linter's rules by disabling these rules, let's fix the codebase instead. Please don't disable it.

2021-07-19 05:54 UTC, rindrajosia commented on src/components/ButtonPanel.js
> +/* eslint-disable react/prop-types */
|REQUIRED] With the ESLint inline comment, you are indirectly changing the linter's rules by disabling these rules, let's fix the codebase instead. Please don't disable it.

2021-07-19 07:31 UTC, Addis0943 commented
Hello TSE
Thank you for your feedback. I did all the changes you requested. kindly review it.

2021-07-19 08:14 UTC, rindrajosia approved these changes
STATUS: APPROVED :heavy_check_mark: :heavy_check_mark:

Good job by working on previous TSEs feedback :tada: . This project is approved. kindly merge and prepare for the next task. Thanks.

**[OPTIONAL] It will be nice if users can make directly a new operation with the previous result in order to get a more useful APP:**
![1](https://user-images.githubusercontent.com/58552748/126126290-f09bdaa3-45ff-4a5d-a6ee-fb284808bc2a.gif)

2021-07-19 08:19 UTC, merged